/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package week_4_tute;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        StringTool tool = new StringTool();
        System.out.println(tool.title("this needs To be A title"));

    }
}
