/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_04_Wed_16_Frank_Group._Assignment2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
