/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_04_Wed_16_Frank_Group._Assignment2;
import java.util.*;

public class App {
    public static void main(String[] args){
        VendingMachine vm = new VendingMachine();
        Scanner scan = new Scanner(System.in);

        vm.setInitialItems();

        UserInterface.displaySnacks(scan, vm.getFood());

    }
}
